from turtle import *

def teglalap(x,y):
    begin_fill()
    forward(x)
    left(90)
    forward(y)
    left(90)
    forward(x)
    left(90)
    forward(y)
    end_fill()

def trikolor(f, k, a):
    fillcolor(f)
    teglalap(400,100)
    up()
    forward(100)
    left(90)
    down()
    fillcolor(k)
    teglalap(400,100)
    up()
    forward(100)
    left(90)
    down()
    fillcolor(a)
    teglalap(400,100)
    left(90)

def dikolor(felso, also):
    fillcolor(felso)
    teglalap(400,150)
    up()
    forward(150)
    left(90)
    down()
    fillcolor(also)
    teglalap(400,150)
    left(90)

def ftrikolor(b, k, j):
    fillcolor(b)
    teglalap(133,300)
    up()
    left(90)
    forward(133)
    down()
    fillcolor(k)
    teglalap(133,300)
    up()
    left(90)
    forward(133)
    down()
    fillcolor(j)
    teglalap(133,300)
    left(90)

reset()
color("gold")
ftrikolor("green","white","orange")
up()
goto(-420,150)
down()
dikolor("white","red")

